const express = require('express');
const router = express.Router();
const bookService = require('../utils/functions');

router.get("/all", bookService.getAllBooks);
router.post('/books', bookService.createBook);
router.get("/countByAuthor", bookService.countByAuthor);
router.get("/sumPricesByAuthor", bookService.sumPricesByAuthor);
router.get("/getAuthorNames", bookService.getAuthorNames);
router.get("/getAllAuthorsThatAreNotEqualToPattern", bookService.getAllAuthorsThatAreNotEqualToPattern);
router.get("/getAllAuthorsAndChangeNameIfEqualToPattern", bookService.getAllAuthorsAndChangeNameIfEqualToPattern);
router.get("/getAllAuthorsThatHavePrice", bookService.getAllAuthorsThatHavePrice);
router.get("/avgPricesAndSum", bookService.avgPricesAndSum);
router.get("/getAllAuthorsThatAreEqualToPattern", bookService.getAllAuthorsThatAreEqualToPattern);
router.get("/getLastTwoDoc", bookService.getLastTwoDoc);
router.get("/multiplyPrices", bookService.multiplyPrices);
router.get("/getFirstAndLastDocs", bookService.getFirstAndLastDocs);
router.get("/getTimeDifferneceBetweenLastTwo", bookService.getTimeDifferneceBetweenLastTwo);
router.get("/getYearFromTimestamp", bookService.getYearFromTimestamp);
router.get("/getLocalTime", bookService.getLocalTime);
module.exports = router;